# DROGHE
#
# Questa sezione è dedicata alla configurazione delle droghe, la struttura è 
# composta da:
# drugs
# └── key (nome della droga)
#     ├── materiale
#     ├── short (danneggio dell'oggetto, esempio INK_SACK con short impostato a 
#     │   2 ha il colore verde scuro; guarda https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/inventory/ItemStack.html) 
#     ├── displayname
#     ├── lore (descrizione) 
#     ├── effetti
#     ├── suono
#     ├── particelle (di default si vede l'oggetto rompersi) NON OBBLIGATORIO
#     ├── prezzo per comprare (da implementare)
#     ├── prezzo per vendere (da implementare)
#     ├── messaggio quando si assume la droga
#     └── dipendeze per assumere la droga (es: per la weed c'è bisogno di 
#         accendino e carta) NON OBBLIGATORIO
#
# Per configurare material, effects, sound e particles, bisogna consultare la 
# documentazione di spigot 1.12.2 https://spigotdocs.okaeri.eu/1.12.2/overview-summary.html
# In particolar modo:
#   - Material https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/Material.html
#   - Effects https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/potion/PotionEffectType.html
#   - Sound https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/Sound.html
#   - Particle https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/Particle.html
#   
# *ATTENZIONE: Bisogna mettere solo il nome in MAIUSCOLO (o come è scritto nella
# documentazione)*
#
# Guardare e capire prima gli esempi sottostanti
drugs:
    cocaine:
        material: SUGAR
        short: 0
        displayname: "&f&lCocaine"
        lore:
            - "&7Ti da un po' di carica!"
        effects:
            - SPEED
        sound: ENTITY_CAT_HISS
        particle: 
        sell-price: 50
        buy-price: 100
        message: "§7Hai assunto la coca"
        dependencies:
        dependencies-extra:
    weed:
        material: INK_SACK
        short: 2
        displayname: "&f&lWeed"
        lore:
            - "Ti da un po' di carica!"
        effects:
            - REGENERATION
            - HUNGER
        sound: BLOCK_FIRE_AMBIENT
        particle: SMOKE_LARGE
        sell-price: 50
        buy-price: 100
        message: "§7Hai fumato la weed"
        dependencies:
            - FLINT_AND_STEEL
            - PAPER  
        dependencies-extra:

# Messaggio di errore quando l'utente ha già assunto una droga
warning_message: "§cVacci piano bello!"

# SEMI
#
# Il ragionamento è analogo a queello delle droghe, è necessario consultare solo 
# la documentazione per i materiali https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/Material.html
#
# *ATTENZIONE: Bisogna mettere solo il nome in MAIUSCOLO (o come è scritto nella
# documentazione)*
#
# Guardare e capire prima gli esempi sottostanti
seeds:
    cocaine:
        material: PUMPKIN_SEEDS
        short: 0
        displayname: "&7&lCocaine seeds"
        lore:
            - "&7Ricorda di zappare il terreno."

# ITEM EXTRA
#
# Il ragionamento è analogo a queello delle droghe, è necessario consultare solo 
# la documentazione per i materiali https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/Material.html
#
# *ATTENZIONE: Bisogna mettere solo il nome in MAIUSCOLO (o come è scritto nella
# documentazione)*
# 
# Con ItemExtra si intendono quei elementi necessarie per il consumo o il 
# crafting di una droga.
#
# Guardare e capire prima gli esempi sottostanti
item-extra:
    ephedrine:
        material: GHAST_TEAR
        short: 0
        displayname: "&f&lEphedrine"
        lore: 
            - "&7Usato per la produzione di metanfetamina."

# CUSTOM DROPS
#
# Questa sezione è dedicata alla configurazione dei drop personalizzata, 
# la struttura è composta da:
# custom-drops
# └── key (nome dell'entità  che dropperà gli oggetti, es: ZOMBIE)
#     ├── override-drops (se `true` sostituisce i drop dell'entità con quelli 
#     │    personalizzati)
#     ├── drugs-drop (lista contenente tutte le droghe che deve droppare l'entità) 
#     │     NON OBBLIGATORIO
#     ├── seeds-drop (ragionamento analogo a drugs-drop) NON OBBLIGATORIO
#     ├── drug-drop-chance (probabilità di drop delle droghe) MINIMO 0
#     └── seed-drop-chance (ragionamento analogo a drug-drop-chance) MINIMO 0
#
# Per configurare key è necessario consultare la documentazione di EntityType 
# https://spigotdocs.okaeri.eu/1.12.2/org/bukkit/entity/EntityType.html
#
# *ATTENZIONE: Bisogna mettere solo il nome in MAIUSCOLO (o come è scritto nella
# documentazione)*
#
# Guardare e capire prima gli esempi sottostanti
custom-drops:
    ZOMBIE: 
        override-drops: false
        ie-drop:
        drugs-drop:
        seeds-drop:
            - cocaine
        ie-drop-chance: 0 #%
        drug-drop-chance: 0 #%
        seed-drop-chance: 35 #%
    CREEPER:
        override-drops: false
        ie-drop: 
            - ephedrine
        drugs-drop:
        seeds-drop:
        ie-drop-chance: 5 #%
        drug-drop-chance: 0 #%
        seed-drop-chance: 0 #%
        